name: github-oke-kubectl
run-name: Testing kubectl run for oke on github
on: [push]
jobs:
  install-kubectl:
    runs-on: ubuntu-latest
    name: Install Kubectl for OKE
    env:
      OCI_CLI_USER: ${{ secrets.OCI_CLI_USER }}
      OCI_CLI_TENANCY: ${{ secrets.OCI_CLI_TENANCY }}
      OCI_CLI_FINGERPRINT: ${{ secrets.OCI_CLI_FINGERPRINT }}
      OCI_CLI_KEY_CONTENT: ${{ secrets.OCI_CLI_KEY_CONTENT }}
      OCI_CLI_REGION: ${{ secrets.OCI_CLI_REGION }}

    steps:

      - name: Get Cluster OCID
        uses: oracle-actions/run-oci-cli-command@v1.1.1 
        id: find-cluster-ocid
        with: 
          command: 'ce cluster list --compartment-id ${{ secrets.OCI_COMPARTMENT_ID }}'
          query: "data[?name=='${{ secrets.OKE_CLUSTER_NAME }}'].id"

      - name: Configure Kubectl
        uses: oracle-actions/configure-kubectl-oke@v1.3.2
        with:
          cluster: ${{ steps.find-cluster-ocid.outputs.raw_output }}

      - name: Run Kubectl
        run: kubectl get nodes -A    